 # This is a basic workflow that is manually triggered

name: POE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
     # list contents or directory
      - name: List contents
        run: ls
     # Compiles classes to test 
      - name: compile classes
        working-directory: ./src
        run: javac -cp "../TestResources/junit-platform-console-standalone-1.6.0.jar" ./hollywood/HollyWood.java ./hollywood/HollyWoodActor.java  "../test/hollywood/HollywoodTest.java"    

    # list contents of src to verify that classess compiled 
      - name: List contents of src directory after compile
        working-directory: ./src/hollywood
        run: ls
        
        # list contents of test to verify that classess compiled 
      - name: List contents of test directory after compile
        working-directory: ./test/hollywood
        run: ls
        
       # copy compiled classes to test directory 
      - name : copy compiled classes to testresources directory 
        working-directory: ./src/hollywood
        run: cp -t "../../test/hollywood/" Hollywood.class HollywoodActor.class
        
        #copy compiled tests 
      - name : copy compiled HollyWoodTest classes to testresources directory 
        working-directory: ./test/hollywood
        run: cp -t  "../../TestResources/" HollywoodTest.class
        
        # list contents or directory
      - name: List contents test package
        working-directory: ./test/hollywood
        run: ls
        
        #run Password Class tests and output report 
      - name: run Hollywood Class tests and create report 
        working-directory: ./test
        run: |
         ls
         java -jar  "../TestResources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class hollywood.HollywoodTest
         
         
